name: lint

on:
  push:
  pull_request:

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install poetry
        uses: snok/install-poetry@v1

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: Install dependencies
        run: poetry install --without docs

      - name: Run pyright
        run: poetry run pyright . --pythonversion ${{ matrix.python-version }}

      - name: Run ruff linter
        run: poetry run ruff check --fix --exit-non-zero-on-fix

      - name: Run ruff formatter
        run: poetry run ruff format --check
